"""
Django settings for learning_log project.

Generated by 'django-admin startproject' using Django 3.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'i!se0-o%i9t@%j-isi@_m___6g%0i!$y!ai_23d0^ue(36z6rz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 我的应用程序
    'learning_logs',
    'users',

    # 第三方应用
    'bootstrap3'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'learning_log.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'learning_log.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'


# 我的设置
LOGIN_URL = '/%5Eusers/login/'

'''如果未登录的用户请求装饰器@login_required的保护页面，Django将重定向到
settings.py中的LOGIN_URL指定的URL。'''

# django-bootstrap3的设置
BOOTSTRAP3 = {
    'include_jquery' : True,
}

'''这些代码让你无需手工下载jQuery并将其放到正确的地方。'''

# 设置图片等静态文件的路径（电脑系统文件夹路径）
STATICFILES_DIRS = (
    "C:/Users/86178/Desktop/Study/Python/learning_log/learning_logs/static/",  
)

# hEROKU的设置
if os.getcwd() == '/app':
    import dj_database_url 
    DATABASES = {
        'default':dj_database_url.config(default='postgres://localhost')
    }

    # 让request.is_secure()承认X-Forwarded-Proto头
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https') 

    # 支持所有的主机头(host header)
    ALLOWED_HOSTS = ['*'] 

    # 静态资产配置
    BASE_DIR = os.path.dirname(os.path.abspath(__file__))
    STATIC_ROOT = 'staticfiles' 
    STATICFILES_DIRS = ( 
        os.path.join(BASE_DIR, 'static'), 
    ) 

'''函数getcwd()，它获取当前的工作目录（当前运行的文件所在的目录）。
在Heroku部署中，这个目录总是/app。在本地部署中，这个目录通常是项目文件夹的名称（就我
们的项目而言，为learning_log）。这个if测试确保仅当项目被部署到Heroku时，才运行这个代码
块。这种结构让我们能够将同一个设置文件用于本地开发环境和在线服务器。

我们导入了dj_database_url，用于在Heroku上配置服务器。Heroku使用PostgreSQL
（也叫Postgres）——一种比SQLite更高级的数据库；这些设置对项目进行配置，使其在Heroku上
使用Postgres数据库。其他设置的作用分别如下：
支持HTTPS请求；
让Django能够使用Heroku的URL来提供项目提供的服务；
设置项目，使其能够在Heroku上正确地提供静态文件'''